services:
  # Observability Stack
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - loki

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - article-service-1
      - article-service-2
      - article-service-3

  # X-axis split: 3 application instances
  article-service-1:
    build: .
    environment:
      - SPRING_APPLICATION_NAME=article-service
    depends_on:
      - zipkin
      - redis
      - rabbitmq
      - postgres-asia
      - postgres-europe
      - postgres-africa
      - postgres-antarctica
      - postgres-north-america
      - postgres-oceania
      - postgres-south-america
      - postgres-global

  article-service-2:
    build: .
    environment:
      - SPRING_APPLICATION_NAME=article-service
    depends_on:
      - zipkin
      - redis
      - rabbitmq
      - postgres-asia
      - postgres-europe
      - postgres-africa
      - postgres-antarctica
      - postgres-north-america
      - postgres-oceania
      - postgres-south-america
      - postgres-global

  article-service-3:
    build: .
    environment:
      - SPRING_APPLICATION_NAME=article-service
    depends_on:
      - zipkin
      - redis
      - rabbitmq
      - postgres-asia
      - postgres-europe
      - postgres-africa
      - postgres-antarctica
      - postgres-north-america
      - postgres-oceania
      - postgres-south-america
      - postgres-global

  # DraftService - separate swimlane
  draft-service:
    build: .
    ports:
      - "8083:8080"
    environment:
      - SPRING_APPLICATION_NAME=draft-service
    depends_on:
      - zipkin
      - rabbitmq
      - postgres-draft

  # PublisherService - separate swimlane
  publisher-service:
    build: .
    ports:
      - "8084:8080"
    environment:
      - SPRING_APPLICATION_NAME=publisher-service
    depends_on:
      - zipkin
      - rabbitmq
      - postgres-draft

  # CommentService - separate swimlane
  comment-service:
    build: .
    ports:
      - "8082:8080"
    depends_on:
      - zipkin
      - redis
      - postgres-comment
      - profanity-service
    environment:
      - SPRING_APPLICATION_NAME=comment-service
      - PROFANITY_SERVICE_URL=http://profanity-service:8080

  # ProfanityService - separate swimlane
  profanity-service:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_APPLICATION_NAME=profanity-service
    depends_on:
      - zipkin
      - postgres-profanity

  # NewsletterService - separate swimlane
  newsletter-service:
    build: .
    ports:
      - "8085:8080"
    environment:
      - SPRING_APPLICATION_NAME=newsletter-service
    depends_on:
      - zipkin
      - nginx

  # DraftDatabase
  postgres-draft:
    image: postgres:17
    environment:
      POSTGRES_DB: draftdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # CommentDatabase
  postgres-comment:
    image: postgres:17
    environment:
      POSTGRES_DB: commentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # ProfanityDatabase
  postgres-profanity:
    image: postgres:17
    environment:
      POSTGRES_DB: profanitydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # Z-axis split: 8 continent databases (7 continents + global)
  postgres-asia:
    image: postgres:17
    environment:
      POSTGRES_DB: articledb_asia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-europe:
    image: postgres:17
    environment:
      POSTGRES_DB: articledb_europe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-africa:
    image: postgres:17
    environment:
      POSTGRES_DB: articledb_africa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-antarctica:
    image: postgres:17
    environment:
      POSTGRES_DB: articledb_antarctica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-north-america:
    image: postgres:17
    environment:
      POSTGRES_DB: articledb_north_america
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-oceania:
    image: postgres:17
    environment:
      POSTGRES_DB: articledb_oceania
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-south-america:
    image: postgres:17
    environment:
      POSTGRES_DB: articledb_south_america
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-global:
    image: postgres:17
    environment:
      POSTGRES_DB: articledb_global
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres