services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: articledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  article-service-1:
    build: .
    depends_on:
      - postgres

  article-service-2:
    build: .
    depends_on:
      - postgres

  article-service-3:
    build: .
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - article-service-1
      - article-service-2
      - article-service-3